#!/bin/bash

#mister clean

find . -type f -name "*~" -delete -o -name "#*#" -delete
find . -type f -name "vgcore.*" -delete
find ~/tek -type f -name NormEZ.rb -delete
find ~/* -type f -name *.o -delete
find . -type f -name "*.pyc" -delete
clear
